---
- name: Restart Nginx
  listen: "restart nginx"
  become: true
  become_user: root
  service:
    name: nginx
    state: restarted

- name: Restart uWSGI
  listen: "restart uwsgi"
  become: true
  become_user: root
  service:
    name: uwsgi
    state: restarted

- name: Restart Dijkstar
  listen: "restart dijkstar"
  become: true
  become_user: root
  service:
    name: dijkstar
    state: restarted
