---
- name: Provision
  hosts:
    - web
  become: true
  roles:
    - provision
  tags:
    - provision

- name: Prepare
  hosts:
    - localhost
  roles:
    - prepare
  tags:
    - prepare

- name: Dijkstar
  hosts:
      - web
  become: true
  become_user: dijkstar
  roles:
      - dijkstar
  tags:
      - dijkstar

- name: Deploy
  hosts:
    - web
  become: true
  become_user: bycycle
  roles:
    - deploy
  tags:
    - deploy
